cabal-version:       3.0
name:                dhall-build
version:             0.2.0.0
synopsis:            Drive the Nix build system with Dhall
homepage:            https://github.com/malikwirin/dhall-build
license:             AGPL-3.0-or-later
license-file:        LICENSE.md
author:              Ollie Charles, Malik Najhi
maintainer:          abdelmalik.najhi@stud.hs-kempten.de
copyright:           2018 Ollie Charles
                     2026 Malik Najhi
build-type:          Simple
extra-source-files:  ChangeLog.md, README.md

common deps
  build-depends:       base
                     , dhall
                     , text
                     , binary
                     , bytestring
                     , network
                     , memory
                     , lens-family-core
                     , containers
                     , nix-derivation
                     , process
                     , attoparsec
                     , cryptonite
                     , mtl
                     , transformers
                     , filepath
                     , insert-ordered-containers
                     , optparse-applicative
                     , MemoTrie
  ghc-options:         -Wall
  default-language:    GHC2024

library
  import:              deps
  exposed-modules:     DhallBuild.DerivationTree
  other-modules:
    MemoIO
    Nix.Daemon
    Nix.Derivations
    Nix.Instantiate
    Nix.StorePath
  hs-source-dirs:      .

executable dhall-build
  import:              deps
  main-is:             dhall-build.hs
  build-depends:       dhall-build

test-suite dhall-build-test
  import:              deps
  type:                exitcode-stdio-1.0
  main-is:             Spec.hs
  hs-source-dirs:      test
  other-modules:       NormalizerSpec
  build-tool-depends:  hspec-discover:hspec-discover
  build-depends:       dhall-build
                     , hspec
		     , dhall
		     , void

