cabal-version:       3.0
name:                dhall-build
version:             0.2.0.0
synopsis:            Drive the Nix build system with Dhall
-- description:
homepage:            https://github.com/malikwirin/dhall-build
license:             AGPL-3.0-or-later
license-file:        LICENSE.md
author:              Ollie Charles, Malik Najhi
maintainer:          abdelmalik.najhi@stud.hs-kempten.de
copyright:	     2018 Ollie Charles
		     2026 Malik Najhi
-- category:
build-type:          Simple
extra-source-files:  ChangeLog.md, README.md
cabal-version:       3.0

executable dhall-build
  main-is:             dhall-build.hs
  other-modules:
    DhallBuild.DerivationTree
    MemoIO
    Nix.Daemon
    Nix.Derivations
    Nix.Instantiate
    Nix.StorePath
  build-depends:       base 
                     , dhall
                     , text
                     , binary
                     , bytestring
                     , network
                     , memory
                     , lens-family-core
                     , containers
                     , nix-derivation
                     , process
                     , attoparsec
                     , cryptonite
                     , mtl
                     , transformers
                     , filepath
                     , insert-ordered-containers
                     , optparse-applicative
                     , MemoTrie
  ghc-options: -Wall
  default-language:    GHC2024
